### ISSUE TITLE
Build error cannot find symbol  method getBinaryMessenger()

### ISSUE THREAD

**Issue by shadyshrif** [MaikuB/flutterfire#1]
> C:\flutter\.pub-cache\git\flutterfire-75018f2629a555d9b1887ec3c10250f7161ffd13\packages\firebase_messaging\android\src\main\java\io\flutter\plugins
> \firebasemessaging\FirebaseMessagingPlugin.java:80: error: cannot find symbol
>     onAttachedToEngine(binding.getApplicationContext(), binding.getBinaryMessenger());
>                                                                ^
>   symbol:   method getBinaryMessenger()
>   location: variable binding of type FlutterPluginBinding
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':firebase_messaging:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

My `flutter doctor -v`

> [√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
>     • Flutter version 1.10.7 at C:\flutter
>     • Framework revision e70236e36c (6 months ago), 2019-10-02 09:32:30 -0700
>     • Engine revision 9e6314d348
>     • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\Administrator.SHADY-LAPTOP\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 39.0.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code (version 1.41.1)
>     • VS Code at C:\Users\Administrator.SHADY-LAPTOP\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.7.1
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> • No issues found!

That issue seems to be in the last commit 75018f2629a555d9b1887ec3c10250f7161ffd13 
This error vanished when I refereed the previous commit cb37d7798b83ae81b3533ea5c1b480b57f94fa08

```
 firebase_messaging:
    git:
      url: https://github.com/MaikuB/flutterfire.git
      path: packages/firebase_messaging
      ref: cb37d7798b83ae81b3533ea5c1b480b57f94fa08
```

**Comment by MaikuB** [comment]
This isn't an issue specific to my fork even though you're using the fork. Those commits were done by the Flutter/Firebase team as I only merged the latest changes back into this fork so I'm not sure why you've raised it here. In any case the issue here is that you're on an older version of Flutter.

**Comment by shadyshrif** [comment]
I didn't know whose code is that, I'm just using your fork as a replacement for the original and got an exception and raised it.
I think they (or maybe you) have to upgrade the required flutter version to avoid developers from getting such an error.

Thanks for your support!

**Comment by MaikuB** [comment]
I'd suggest you raise it back on the main repository. May be possible that the version you were using actually should have the referenced API but need to run `flutter upgrade` but I haven't tried that channel and it's likely beta is ahead of that version now given stable is on 1.12
